language: python

before_install:
  - sudo apt-get install -y gfortran

addons:
  apt:
    packages:
    - gcc
  homebrew:
    packages:
    - gcc

os:
  - linux
  - osx

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .

script: pytest

